# name: create-diagram

# on:
#   push:
#     branches:
#       - master
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Create a diagram
#       uses: githubocto/repo-visualizer@main
#       with:
#         output_file: docs/_static/code-diagram.svg
